# [dein_lazy.toml]

# python
# ------

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = 'python'

# toml
# ----

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# Markdown
# --------

# 基本機能の提供
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_no_default_key_mappings = 1
let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_folding_style_pythonic = 1
'''

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown', 'mkd']

# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']
hook_add = '''
let g:previm_disable_default_css = 1
let g:previm_custom_css_path = '~/dotfiles/vim/previm/markdown.css'
'''

# プレビューをブラウザで開いてくれる
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']



